# Generated by Django 2.2.4 on 2020-05-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Castrated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color_palette', models.CharField(max_length=10)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=50)),
                ('image2', models.CharField(max_length=50)),
                ('image3', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('unique_characteristics', models.TextField(max_length=500)),
                ('surgery', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('found_location', models.CharField(max_length=50)),
                ('welcome_date', models.DateTimeField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Age')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Breed')),
                ('castrated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Castrated')),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='app_animal.Color')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Disease')),
                ('how_was_it_welcomed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_was_it_welcomed', to='app_animal.Species')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.UserType')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Sex')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Size')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='app_animal.Species')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Status')),
                ('treatments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_animal.Treatments')),
            ],
        ),
    ]
