# Generated by Django 2.2.4 on 2020-05-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='app_animal.Color'),
        ),
        migrations.AddField(
            model_name='animal',
            name='color3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='app_animal.Color'),
        ),
    ]
