# Generated by Django 2.2.4 on 2020-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('name_fantasy', models.CharField(max_length=100)),
                ('name_social', models.CharField(max_length=100)),
                ('cell', models.IntegerField()),
                ('dt_foundation', models.DateTimeField()),
                ('cnpj', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
